### ISSUE TITLE
[Insight] The composer.json file should not raise warnings - in composer.json, line 0

### ISSUE THREAD

**Issue by CoalaJoe** [PReimers/ict-scouts#13]
**[in composer.json](https://github.com/PReimers/ict-scouts/blob/3c80e895c89b06b625be36e90c3e420879f1d1b9/composer.json#L0)**

> The version field is present, it is recommended to leave it out if the package is published on Packagist.

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/83636cb1-9998-402c-bb9b-7f8b215b1bfd/analyses/59)_

@PReimers Should we ignore it?

**Comment by PReimers** [comment]
@CoallaJoe 
Ja, ignorieren hört sich hier gut an.

**Comment by PReimers** [comment]
Habe es im Insight ignoriert 😄
