### ISSUE TITLE
Überladene User Klasse

### ISSUE THREAD

**Issue by CoalaJoe** [PReimers/ict-scouts#15]
Ich finde wir sollten die User Klasse überarbeiten. 
- Sie bietet zu viele setter an. Diese würde ich in den Constructor auslagern.
- getUsername Funktion ist einwenig unschön gelöst.

**Comment by PReimers** [comment]
Die User-Klasse ist ja eine Entity und braucht eigentlich alle setter.

Die getUsername-Funktion wird vom UserInterface gefordert und eigentlich nicht ordentlich genutzt.
Aktuell wird hier also der volle Name des Benutzers zurückgegeben.

**Comment by CoalaJoe** [comment]
Nein, die Setter werden nicht benötigt. Doctrine erstellt die Objekte ohne Construktor.

Für den Benutzernamen habe ich an den Teil der E-Mail Addresse gedacht welcher vor dem @ ist.

**Comment by PReimers** [comment]
Wenn Werte gesetzt/aktualisiert werden sollen/müssen, braucht es setter. 

Da der Benutzername nicht benutzt wird, kann man dies aktuell nutzen, um z.B. den Namen des Benutzers in logs zu hinterlegen.

**Comment by CoalaJoe** [comment]
http://www.doctrine-project.org/2010/03/21/doctrine-2-give-me-my-constructor-back.html

wenn wir das als Benutzernamen nehmen können wir auch so auf die Profile verweisen. Ausserdem sind diese bereits einzigartig.
