### ISSUE TITLE
Test Deployment

### ISSUE THREAD

**Issue by PReimers** [PReimers/ict-scouts#17]
Die Test Applikation muss am Git angebunden und mit den korrekten Google Zugangsdaten eingerichtet werden.

**Comment by PReimers** [comment]
SSH Verbindung ist auf dem Server aktuell nicht möglich.

Bin schon in der Klärung.

**Comment by PReimers** [comment]
In der Zwischenzeit habe ich Zugang zum Server erhalten, es gibt aber noch ein kleines Problem.

```php-fpm``` (web) ist auf 7.0, ```php-cli``` (terminal) ist auf Version 5.5.9.
Wir brauchen aber ```php >= 7.0``` :disappointed:

**Comment by CoalaJoe** [comment]
...

**Comment by PReimers** [comment]
Das Release hat sich gerade hinten geschoben.

Im Frühjahr wird der Server geupdated.
Dann erhalten wir PHP 7.0.

Bis dahin heisst es warten.. :smile: & Testen auf einem meiner Server.. :disappointed:

**Comment by CoalaJoe** [comment]
Aber hey. Dann haben wir Zeit für die Modals ;)

**Comment by PReimers** [comment]
Aktuell wird das Deployment der Testumgebung auf einem Alternativem Server durchgeführt.
