### ISSUE TITLE
Installationsanleitung

### ISSUE THREAD

**Issue by CoalaJoe** [PReimers/ict-scouts#21]
Step-by-step Anleitungs und Erklährung der Orderstruktur.

**Comment by PReimers** [comment]
@CoalaJoe 

Kannst du auch eine Contribution-Anleitung schreiben?

Also Info, über Fork-Architektur, Feature-Branches, Issues, Pull-Requests, [Waffle](https://waffle.io/PReimers/ict-scouts), ...
