### ISSUE TITLE
Konsistenz.

### ISSUE THREAD

**Issue by CoalaJoe** [PReimers/ict-scouts#22]
Ich würde vorschlagen den `GoogleHelper` zu `GoogleService` umzubenennen und ihn in einen Service-Ordner zu tun. Tendenziell wird es mehrere Services geben und 1 Order wo alle Services drin sind, finde ich verständlicher. Feedback?

**Comment by PReimers** [comment]
Ob wir es service, helper oder irgendwie anders nennen ist ja eigentlich egal, wir müssen nur wissen, was es macht 😄

**Comment by CoalaJoe** [comment]
Ja, die Benennung ist eigentlich egal. Standartmässig werden sie aber in Bundles Service genannt, da es Services sind.

**Comment by PReimers** [comment]
Ich werde mich mal morgen dran setzen und den `GoogleHelper` umbenennen und in mehrere Services splitten (GoogleService & GoogleUserService) 😉

**Comment by CoalaJoe** [comment]
Super. Danke
