### ISSUE TITLE
[Insight] Deprecated class usage found - in src/AppBundle/Entity/Group.php, line 16

### ISSUE THREAD

**Issue by PReimers** [PReimers/ict-scouts#37]
**[in src/AppBundle/Entity/Group.php, line 16](https://github.com/PReimers/ict-scouts/blob/9dfbfe3511530544184df62b20664aafb673a11a/src/AppBundle/Entity/Group.php#L16)**

> The `Symfony\Component\Security\Core\Role\RoleInterface` class has been deprecated in Symfony 3.3. Use the `Symfony\Component\Security\Core\Role\Role` class instead.

```php
 * Class Group.
 *
 * @ORM\Table(name="app_group")
 * @ORM\Entity
 */
class Group implements RoleInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/83636cb1-9998-402c-bb9b-7f8b215b1bfd/analyses/126)_

**Comment by PReimers** [comment]
@CoalaJoe 
Status?

**Comment by CoalaJoe** [comment]
@PReimers Pendent.
