### ISSUE TITLE
PLZ Verzeichnis der Post einlesen

### ISSUE THREAD

**Issue by PReimers** [PReimers/ict-scouts#46]
Das PLZ Verzeichnis der Post muss eingelesen werden.

Folgende Daten brauchen wir:
* Eindeutige ID (darf sich beim neu einlesen nicht ändern)
* PLZ
* Ort
* (ggf. Verknüpfung auf Kanton-Tabelle)

Ein (aktuelles) Verzeichnis ist angehängt 😄 
[Post_Adressdaten-20170307.zip](https://github.com/PReimers/ict-scouts/files/951578/Post_Adressdaten-20170307.zip)

**Comment by PReimers** [comment]
Ich würde sagen am besten ist es wenn ein Fixture erstellt wird, welches die Daten direkt aus dem File ausliesst.

**Comment by CoalaJoe** [comment]
Es gibt einen neuen branch "feature/zip-fixtures".
Man muss sich noch überlegen wie man das macht wegen dem csv file. Ich habe es nicht ins git aufgenommen wegen der Grösse. Die Tests werden ohne diese Datei fehlschlagen.

**Comment by PReimers** [comment]
@CoalaJoe 
Was sagst du zur Idee das CSV-File per Google-Drive (web freigabe) zu downloaden?

**Comment by CoalaJoe** [comment]
👍

**Comment by PReimers** [comment]
@CoalaJoe 
Weisst du wie es sich mit der URL (freigabelink) verhält, wenn sich das File ändert (neue version hochladen)? 🤔

**Comment by CoalaJoe** [comment]
Keine Ahnung

**Comment by PReimers** [comment]
Ich glaube das sollten wir vorher testen 🤔

**Comment by CoalaJoe** [comment]
👍

**Comment by PReimers** [comment]
Habe es gerade getestet 👍 

Es funktioniert, wenn man mit der Versionisierung schafft 😄

**Comment by CoalaJoe** [comment]
Gut.
